/* SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause) */

/* THIS FILE IS AUTOGENERATED BY BPFTOOL! */
#ifndef __TEST_EBPF_SKEL_H__
#define __TEST_EBPF_SKEL_H__

#include <errno.h>
#include <stdlib.h>
#include <bpf/libbpf.h>

#define BPF_SKEL_SUPPORTS_MAP_AUTO_ATTACH 1

struct test_ebpf {
	struct bpf_object_skeleton *skeleton;
	struct bpf_object *obj;
	struct {
		struct bpf_map *rodata;
	} maps;
	struct {
		struct bpf_program *trace_system_enter;
	} progs;
	struct {
		struct bpf_link *trace_system_enter;
	} links;

#ifdef __cplusplus
	static inline struct test_ebpf *open(const struct bpf_object_open_opts *opts = nullptr);
	static inline struct test_ebpf *open_and_load();
	static inline int load(struct test_ebpf *skel);
	static inline int attach(struct test_ebpf *skel);
	static inline void detach(struct test_ebpf *skel);
	static inline void destroy(struct test_ebpf *skel);
	static inline const void *elf_bytes(size_t *sz);
#endif /* __cplusplus */
};

static void
test_ebpf__destroy(struct test_ebpf *obj)
{
	if (!obj)
		return;
	if (obj->skeleton)
		bpf_object__destroy_skeleton(obj->skeleton);
	free(obj);
}

static inline int
test_ebpf__create_skeleton(struct test_ebpf *obj);

static inline struct test_ebpf *
test_ebpf__open_opts(const struct bpf_object_open_opts *opts)
{
	struct test_ebpf *obj;
	int err;

	obj = (struct test_ebpf *)calloc(1, sizeof(*obj));
	if (!obj) {
		errno = ENOMEM;
		return NULL;
	}

	err = test_ebpf__create_skeleton(obj);
	if (err)
		goto err_out;

	err = bpf_object__open_skeleton(obj->skeleton, opts);
	if (err)
		goto err_out;

	return obj;
err_out:
	test_ebpf__destroy(obj);
	errno = -err;
	return NULL;
}

static inline struct test_ebpf *
test_ebpf__open(void)
{
	return test_ebpf__open_opts(NULL);
}

static inline int
test_ebpf__load(struct test_ebpf *obj)
{
	return bpf_object__load_skeleton(obj->skeleton);
}

static inline struct test_ebpf *
test_ebpf__open_and_load(void)
{
	struct test_ebpf *obj;
	int err;

	obj = test_ebpf__open();
	if (!obj)
		return NULL;
	err = test_ebpf__load(obj);
	if (err) {
		test_ebpf__destroy(obj);
		errno = -err;
		return NULL;
	}
	return obj;
}

static inline int
test_ebpf__attach(struct test_ebpf *obj)
{
	return bpf_object__attach_skeleton(obj->skeleton);
}

static inline void
test_ebpf__detach(struct test_ebpf *obj)
{
	bpf_object__detach_skeleton(obj->skeleton);
}

static inline const void *test_ebpf__elf_bytes(size_t *sz);

static inline int
test_ebpf__create_skeleton(struct test_ebpf *obj)
{
	struct bpf_object_skeleton *s;
	struct bpf_map_skeleton *map __attribute__((unused));
	int err;

	s = (struct bpf_object_skeleton *)calloc(1, sizeof(*s));
	if (!s)	{
		err = -ENOMEM;
		goto err;
	}

	s->sz = sizeof(*s);
	s->name = "test_ebpf";
	s->obj = &obj->obj;

	/* maps */
	s->map_cnt = 1;
	s->map_skel_sz = 24;
	s->maps = (struct bpf_map_skeleton *)calloc(s->map_cnt,
			sizeof(*s->maps) > 24 ? sizeof(*s->maps) : 24);
	if (!s->maps) {
		err = -ENOMEM;
		goto err;
	}

	map = (struct bpf_map_skeleton *)((char *)s->maps + 0 * s->map_skel_sz);
	map->name = "test_ebp.rodata";
	map->map = &obj->maps.rodata;

	/* programs */
	s->prog_cnt = 1;
	s->prog_skel_sz = sizeof(*s->progs);
	s->progs = (struct bpf_prog_skeleton *)calloc(s->prog_cnt, s->prog_skel_sz);
	if (!s->progs) {
		err = -ENOMEM;
		goto err;
	}

	s->progs[0].name = "trace_system_enter";
	s->progs[0].prog = &obj->progs.trace_system_enter;
	s->progs[0].link = &obj->links.trace_system_enter;

	s->data = test_ebpf__elf_bytes(&s->data_sz);

	obj->skeleton = s;
	return 0;
err:
	bpf_object__destroy_skeleton(s);
	return err;
}

static inline const void *test_ebpf__elf_bytes(size_t *sz)
{
	static const char data[] __attribute__((__aligned__(8))) = "\
\x7f\x45\x4c\x46\x02\x01\x01\0\0\0\0\0\0\0\0\0\x01\0\xf7\0\x01\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\xb8\x0d\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\x40\0\x1b\0\
\x01\0\x85\0\0\0\x0e\0\0\0\xbf\x03\0\0\0\0\0\0\x77\x03\0\0\x20\0\0\0\x18\x01\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\xb7\x02\0\0\x23\0\0\0\xbf\x04\0\0\0\0\0\0\x85\0\0\0\
\x06\0\0\0\xb7\0\0\0\0\0\0\0\x95\0\0\0\0\0\0\0\x5b\x50\x49\x44\x20\x25\x64\x5d\
\x20\x5b\x54\x49\x44\x20\x25\x64\x5d\x20\x65\x6e\x74\x65\x72\x65\x64\x20\x73\
\x79\x73\x63\x61\x6c\x6c\x21\0\x47\x50\x4c\0\x1c\0\0\0\x05\0\x08\0\x02\0\0\0\
\x08\0\0\0\x0e\0\0\0\x04\x08\x40\x01\x50\0\x04\x08\x40\x01\x50\0\x01\x11\x01\
\x25\x25\x13\x05\x03\x25\x72\x17\x10\x17\x1b\x25\x11\x1b\x12\x06\x73\x17\x8c\
\x01\x17\0\0\x02\x34\0\x03\x25\x49\x13\x3a\x0b\x3b\x05\0\0\x03\x26\0\x49\x13\0\
\0\x04\x0f\0\x49\x13\0\0\x05\x15\0\x49\x13\x27\x19\0\0\x06\x16\0\x49\x13\x03\
\x25\x3a\x0b\x3b\x05\0\0\x07\x24\0\x03\x25\x3e\x0b\x0b\x0b\0\0\x08\x2e\x01\x11\
\x1b\x12\x06\x40\x18\x7a\x19\x03\x25\x3a\x0b\x3b\x0b\x27\x19\x49\x13\x3f\x19\0\
\0\x09\x34\0\x03\x25\x49\x13\x3a\x0b\x3b\x0b\x02\x18\0\0\x0a\x05\0\x03\x25\x3a\
\x0b\x3b\x0b\x49\x13\0\0\x0b\x34\0\x02\x22\x03\x25\x3a\x0b\x3b\x0b\x49\x13\0\0\
\x0c\x34\0\x03\x25\x3a\x0b\x3b\x0b\x49\x13\0\0\x0d\x01\x01\x49\x13\0\0\x0e\x21\
\0\x49\x13\x37\x0b\0\0\x0f\x24\0\x03\x25\x0b\x0b\x3e\x0b\0\0\x10\x34\0\x03\x25\
\x49\x13\x3a\x0b\x3b\x0b\0\0\x11\x15\x01\x49\x13\x27\x19\0\0\x12\x05\0\x49\x13\
\0\0\x13\x18\0\0\0\x14\x34\0\x03\x25\x49\x13\x3f\x19\x3a\x0b\x3b\x0b\x02\x18\0\
\0\x15\x0f\0\0\0\0\x06\x01\0\0\x05\0\x01\x08\0\0\0\0\x01\0\x1d\0\x01\x08\0\0\0\
\0\0\0\0\x02\x02\x50\0\0\0\x08\0\0\0\x0c\0\0\0\x02\x03\x30\0\0\0\x02\x7a\x01\
\x03\x35\0\0\0\x04\x3a\0\0\0\x05\x3f\0\0\0\x06\x48\0\0\0\x05\x01\xf7\x62\x07\
\x04\x07\x08\x08\x02\x50\0\0\0\x01\x5a\x0f\0\x06\xfb\0\0\0\x09\x06\x89\0\0\0\0\
\x0c\x02\xa1\0\x0a\x14\0\x06\x08\x01\0\0\x0b\0\x11\0\x0a\xf2\0\0\0\x0b\x01\x12\
\0\x08\xff\0\0\0\x0c\x15\0\x09\xf2\0\0\0\0\x0d\x95\0\0\0\x0e\x9e\0\0\0\x23\0\
\x03\x9a\0\0\0\x07\x07\x06\x01\x0f\x08\x08\x07\x10\x09\xaa\0\0\0\x02\xb9\x03\
\xaf\0\0\0\x04\xb4\0\0\0\x11\xc5\0\0\0\x12\xc9\0\0\0\x12\xce\0\0\0\x13\0\x07\
\x0a\x05\x08\x04\x95\0\0\0\x06\xd7\0\0\0\x0c\x01\x2f\x64\x07\x0b\x07\x04\x14\
\x0d\xe6\0\0\0\0\x10\x02\xa1\x01\x0d\x9a\0\0\0\x0e\x9e\0\0\0\x04\0\x06\xce\0\0\
\0\x0e\x01\x3d\x64\x07\x10\x05\x04\x06\x3f\0\0\0\x13\x01\xff\x62\x15\0\x5c\0\0\
\0\x05\0\0\0\0\0\0\0\x23\0\0\0\x2e\0\0\0\x46\0\0\0\x5f\0\0\0\x72\0\0\0\x78\0\0\
\0\x80\0\0\0\x85\0\0\0\x99\0\0\0\xaa\0\0\0\xaf\0\0\0\xbc\0\0\0\xc2\0\0\0\xca\0\
\0\0\xce\0\0\0\xe1\0\0\0\xe5\0\0\0\xe9\0\0\0\xf2\0\0\0\xf6\0\0\0\xfa\0\0\0\x44\
\x65\x62\x69\x61\x6e\x20\x63\x6c\x61\x6e\x67\x20\x76\x65\x72\x73\x69\x6f\x6e\
\x20\x31\x39\x2e\x31\x2e\x37\x20\x28\x33\x2b\x62\x31\x29\0\x74\x65\x73\x74\x2e\
\x62\x70\x66\x2e\x63\0\x2f\x68\x6f\x6d\x65\x2f\x6b\x6b\x74\x6f\x72\x69\x2f\x6c\
\x65\x61\x72\x6e\x2f\x65\x42\x50\x46\0\x62\x70\x66\x5f\x67\x65\x74\x5f\x63\x75\
\x72\x72\x65\x6e\x74\x5f\x70\x69\x64\x5f\x74\x67\x69\x64\0\x75\x6e\x73\x69\x67\
\x6e\x65\x64\x20\x6c\x6f\x6e\x67\x20\x6c\x6f\x6e\x67\0\x5f\x5f\x75\x36\x34\0\
\x5f\x5f\x5f\x5f\x66\x6d\x74\0\x63\x68\x61\x72\0\x5f\x5f\x41\x52\x52\x41\x59\
\x5f\x53\x49\x5a\x45\x5f\x54\x59\x50\x45\x5f\x5f\0\x62\x70\x66\x5f\x74\x72\x61\
\x63\x65\x5f\x70\x72\x69\x6e\x74\x6b\0\x6c\x6f\x6e\x67\0\x75\x6e\x73\x69\x67\
\x6e\x65\x64\x20\x69\x6e\x74\0\x5f\x5f\x75\x33\x32\0\x4c\x49\x43\x45\x4e\x53\
\x45\0\x75\x33\x32\0\x74\x72\x61\x63\x65\x5f\x73\x79\x73\x74\x65\x6d\x5f\x65\
\x6e\x74\x65\x72\0\x69\x6e\x74\0\x74\x69\x64\0\x70\x69\x64\x5f\x74\x67\x69\x64\
\0\x75\x36\x34\0\x63\x74\x78\0\x70\x69\x64\0\x1c\0\0\0\x05\0\x08\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x9f\xeb\x01\0\x18\0\0\0\0\0\0\0\xe8\0\
\0\0\xe8\0\0\0\x3a\x01\0\0\0\0\0\0\0\0\0\x02\0\0\0\0\0\0\0\0\x01\0\0\x0d\x03\0\
\0\0\x01\0\0\0\x01\0\0\0\x05\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\x01\x09\0\0\0\
\x01\0\0\x0c\x02\0\0\0\0\0\0\0\0\0\0\x0a\x06\0\0\0\xee\0\0\0\0\0\0\x01\x01\0\0\
\0\x08\0\0\x01\0\0\0\0\0\0\0\x03\0\0\0\0\x05\0\0\0\x08\0\0\0\x23\0\0\0\xf3\0\0\
\0\0\0\0\x01\x04\0\0\0\x20\0\0\0\x07\x01\0\0\0\0\0\x0e\x07\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\x03\0\0\0\0\x06\0\0\0\x08\0\0\0\x04\0\0\0\x22\x01\0\0\0\0\0\x0e\x0a\0\
\0\0\x01\0\0\0\x2a\x01\0\0\x01\0\0\x0f\0\0\0\0\x09\0\0\0\0\0\0\0\x23\0\0\0\x32\
\x01\0\0\x01\0\0\x0f\0\0\0\0\x0b\0\0\0\0\0\0\0\x04\0\0\0\0\x63\x74\x78\0\x69\
\x6e\x74\0\x74\x72\x61\x63\x65\x5f\x73\x79\x73\x74\x65\x6d\x5f\x65\x6e\x74\x65\
\x72\0\x72\x61\x77\x5f\x74\x70\x2f\x73\x79\x73\x5f\x65\x6e\x74\x65\x72\0\x2f\
\x68\x6f\x6d\x65\x2f\x6b\x6b\x74\x6f\x72\x69\x2f\x6c\x65\x61\x72\x6e\x2f\x65\
\x42\x50\x46\x2f\x74\x65\x73\x74\x2e\x62\x70\x66\x2e\x63\0\x20\x20\x20\x20\x75\
\x36\x34\x20\x70\x69\x64\x5f\x74\x67\x69\x64\x20\x3d\x20\x62\x70\x66\x5f\x67\
\x65\x74\x5f\x63\x75\x72\x72\x65\x6e\x74\x5f\x70\x69\x64\x5f\x74\x67\x69\x64\
\x28\x29\x3b\0\x20\x20\x20\x20\x75\x33\x32\x20\x70\x69\x64\x20\x3d\x20\x70\x69\
\x64\x5f\x74\x67\x69\x64\x20\x3e\x3e\x20\x33\x32\x3b\0\x20\x20\x20\x20\x62\x70\
\x66\x5f\x70\x72\x69\x6e\x74\x6b\x28\x22\x5b\x50\x49\x44\x20\x25\x64\x5d\x20\
\x5b\x54\x49\x44\x20\x25\x64\x5d\x20\x65\x6e\x74\x65\x72\x65\x64\x20\x73\x79\
\x73\x63\x61\x6c\x6c\x21\x22\x2c\x20\x70\x69\x64\x2c\x20\x74\x69\x64\x29\x3b\0\
\x20\x20\x20\x20\x72\x65\x74\x75\x72\x6e\x20\x30\x3b\x20\x20\x20\0\x63\x68\x61\
\x72\0\x5f\x5f\x41\x52\x52\x41\x59\x5f\x53\x49\x5a\x45\x5f\x54\x59\x50\x45\x5f\
\x5f\0\x74\x72\x61\x63\x65\x5f\x73\x79\x73\x74\x65\x6d\x5f\x65\x6e\x74\x65\x72\
\x2e\x5f\x5f\x5f\x5f\x66\x6d\x74\0\x4c\x49\x43\x45\x4e\x53\x45\0\x2e\x72\x6f\
\x64\x61\x74\x61\0\x6c\x69\x63\x65\x6e\x73\x65\0\0\0\x9f\xeb\x01\0\x20\0\0\0\0\
\0\0\0\x14\0\0\0\x14\0\0\0\x4c\0\0\0\x60\0\0\0\0\0\0\0\x08\0\0\0\x1c\0\0\0\x01\
\0\0\0\0\0\0\0\x04\0\0\0\x10\0\0\0\x1c\0\0\0\x04\0\0\0\0\0\0\0\x2d\0\0\0\x50\0\
\0\0\x14\x20\0\0\x08\0\0\0\x2d\0\0\0\x7f\0\0\0\x18\x24\0\0\x18\0\0\0\x2d\0\0\0\
\x9d\0\0\0\x05\x30\0\0\x40\0\0\0\x2d\0\0\0\xdd\0\0\0\x05\x34\0\0\x0c\0\0\0\xff\
\xff\xff\xff\x04\0\x08\0\x08\x7c\x0b\0\x14\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x50\0\
\0\0\0\0\0\0\x8e\0\0\0\x05\0\x08\0\x69\0\0\0\x08\x01\x01\xfb\x0e\x0d\0\x01\x01\
\x01\x01\0\0\0\x01\0\0\x01\x01\x01\x1f\x03\0\0\0\0\x18\0\0\0\x1a\0\0\0\x03\x01\
\x1f\x02\x0f\x05\x1e\x03\x2b\0\0\0\0\x1a\x3d\x7e\x39\x43\x95\x35\x7d\xc6\xd5\
\xb0\x5d\xe7\xec\x0a\x0e\x36\0\0\0\x01\x4f\xe6\x4b\x08\xb1\xe8\x47\xaa\xe4\x88\
\x80\xd5\x86\xbc\xfa\x32\x40\0\0\0\x02\xa5\xa8\xa4\xf9\x34\xaa\x57\x11\xde\xc2\
\x3f\xec\x64\x5c\x40\x01\x04\0\x05\x14\x0a\0\x09\x02\0\0\0\0\0\0\0\0\x19\x05\
\x18\x21\x05\x05\x31\x59\x02\x02\0\x01\x01\x2f\x68\x6f\x6d\x65\x2f\x6b\x6b\x74\
\x6f\x72\x69\x2f\x6c\x65\x61\x72\x6e\x2f\x65\x42\x50\x46\0\x2e\0\x2f\x75\x73\
\x72\x2f\x69\x6e\x63\x6c\x75\x64\x65\x2f\x62\x70\x66\0\x74\x65\x73\x74\x2e\x62\
\x70\x66\x2e\x63\0\x76\x6d\x6c\x69\x6e\x75\x78\x2e\x68\0\x62\x70\x66\x5f\x68\
\x65\x6c\x70\x65\x72\x5f\x64\x65\x66\x73\x2e\x68\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xfe\0\0\0\x04\0\xf1\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\x03\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x22\0\0\0\x01\0\x05\
\0\0\0\0\0\0\0\0\0\x23\0\0\0\0\0\0\0\0\0\0\0\x03\0\x05\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\x03\0\x07\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\
\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\x0b\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\x03\0\x0d\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\
\x0e\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\x14\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\x03\0\x16\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\
\x18\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x94\0\0\0\x12\0\x03\0\0\0\0\0\0\0\0\0\
\x50\0\0\0\0\0\0\0\x2a\x01\0\0\x11\0\x06\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\
\x18\0\0\0\0\0\0\0\x01\0\0\0\x04\0\0\0\x08\0\0\0\0\0\0\0\x03\0\0\0\x06\0\0\0\
\x11\0\0\0\0\0\0\0\x03\0\0\0\x07\0\0\0\x15\0\0\0\0\0\0\0\x03\0\0\0\x0b\0\0\0\
\x1f\0\0\0\0\0\0\0\x03\0\0\0\x09\0\0\0\x23\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\
\x08\0\0\0\0\0\0\0\x03\0\0\0\x08\0\0\0\x0c\0\0\0\0\0\0\0\x03\0\0\0\x08\0\0\0\
\x10\0\0\0\0\0\0\0\x03\0\0\0\x08\0\0\0\x14\0\0\0\0\0\0\0\x03\0\0\0\x08\0\0\0\
\x18\0\0\0\0\0\0\0\x03\0\0\0\x08\0\0\0\x1c\0\0\0\0\0\0\0\x03\0\0\0\x08\0\0\0\
\x20\0\0\0\0\0\0\0\x03\0\0\0\x08\0\0\0\x24\0\0\0\0\0\0\0\x03\0\0\0\x08\0\0\0\
\x28\0\0\0\0\0\0\0\x03\0\0\0\x08\0\0\0\x2c\0\0\0\0\0\0\0\x03\0\0\0\x08\0\0\0\
\x30\0\0\0\0\0\0\0\x03\0\0\0\x08\0\0\0\x34\0\0\0\0\0\0\0\x03\0\0\0\x08\0\0\0\
\x38\0\0\0\0\0\0\0\x03\0\0\0\x08\0\0\0\x3c\0\0\0\0\0\0\0\x03\0\0\0\x08\0\0\0\
\x40\0\0\0\0\0\0\0\x03\0\0\0\x08\0\0\0\x44\0\0\0\0\0\0\0\x03\0\0\0\x08\0\0\0\
\x48\0\0\0\0\0\0\0\x03\0\0\0\x08\0\0\0\x4c\0\0\0\0\0\0\0\x03\0\0\0\x08\0\0\0\
\x50\0\0\0\0\0\0\0\x03\0\0\0\x08\0\0\0\x54\0\0\0\0\0\0\0\x03\0\0\0\x08\0\0\0\
\x58\0\0\0\0\0\0\0\x03\0\0\0\x08\0\0\0\x5c\0\0\0\0\0\0\0\x03\0\0\0\x08\0\0\0\
\x08\0\0\0\0\0\0\0\x02\0\0\0\x04\0\0\0\x10\0\0\0\0\0\0\0\x02\0\0\0\x0e\0\0\0\
\x18\0\0\0\0\0\0\0\x02\0\0\0\x02\0\0\0\xe0\0\0\0\0\0\0\0\x03\0\0\0\x04\0\0\0\
\xf8\0\0\0\0\0\0\0\x04\0\0\0\x0e\0\0\0\x2c\0\0\0\0\0\0\0\x04\0\0\0\x02\0\0\0\
\x40\0\0\0\0\0\0\0\x04\0\0\0\x02\0\0\0\x50\0\0\0\0\0\0\0\x04\0\0\0\x02\0\0\0\
\x60\0\0\0\0\0\0\0\x04\0\0\0\x02\0\0\0\x70\0\0\0\0\0\0\0\x04\0\0\0\x02\0\0\0\
\x14\0\0\0\0\0\0\0\x03\0\0\0\x0a\0\0\0\x18\0\0\0\0\0\0\0\x02\0\0\0\x02\0\0\0\
\x22\0\0\0\0\0\0\0\x03\0\0\0\x0c\0\0\0\x26\0\0\0\0\0\0\0\x03\0\0\0\x0c\0\0\0\
\x2a\0\0\0\0\0\0\0\x03\0\0\0\x0c\0\0\0\x36\0\0\0\0\0\0\0\x03\0\0\0\x0c\0\0\0\
\x4b\0\0\0\0\0\0\0\x03\0\0\0\x0c\0\0\0\x60\0\0\0\0\0\0\0\x03\0\0\0\x0c\0\0\0\
\x7d\0\0\0\0\0\0\0\x02\0\0\0\x02\0\0\0\x0d\x03\x0e\0\x2e\x64\x65\x62\x75\x67\
\x5f\x61\x62\x62\x72\x65\x76\0\x2e\x74\x65\x78\x74\0\x2e\x72\x65\x6c\x2e\x42\
\x54\x46\x2e\x65\x78\x74\0\x74\x72\x61\x63\x65\x5f\x73\x79\x73\x74\x65\x6d\x5f\
\x65\x6e\x74\x65\x72\x2e\x5f\x5f\x5f\x5f\x66\x6d\x74\0\x2e\x64\x65\x62\x75\x67\
\x5f\x6c\x6f\x63\x6c\x69\x73\x74\x73\0\x2e\x72\x65\x6c\x2e\x64\x65\x62\x75\x67\
\x5f\x73\x74\x72\x5f\x6f\x66\x66\x73\x65\x74\x73\0\x2e\x64\x65\x62\x75\x67\x5f\
\x73\x74\x72\0\x2e\x64\x65\x62\x75\x67\x5f\x6c\x69\x6e\x65\x5f\x73\x74\x72\0\
\x2e\x72\x65\x6c\x72\x61\x77\x5f\x74\x70\x2f\x73\x79\x73\x5f\x65\x6e\x74\x65\
\x72\0\x74\x72\x61\x63\x65\x5f\x73\x79\x73\x74\x65\x6d\x5f\x65\x6e\x74\x65\x72\
\0\x2e\x72\x65\x6c\x2e\x64\x65\x62\x75\x67\x5f\x61\x64\x64\x72\0\x2e\x72\x65\
\x6c\x2e\x64\x65\x62\x75\x67\x5f\x69\x6e\x66\x6f\0\x2e\x6c\x6c\x76\x6d\x5f\x61\
\x64\x64\x72\x73\x69\x67\0\x6c\x69\x63\x65\x6e\x73\x65\0\x2e\x72\x65\x6c\x2e\
\x64\x65\x62\x75\x67\x5f\x6c\x69\x6e\x65\0\x2e\x72\x65\x6c\x2e\x64\x65\x62\x75\
\x67\x5f\x66\x72\x61\x6d\x65\0\x74\x65\x73\x74\x2e\x62\x70\x66\x2e\x63\0\x2e\
\x73\x74\x72\x74\x61\x62\0\x2e\x73\x79\x6d\x74\x61\x62\0\x2e\x72\x6f\x64\x61\
\x74\x61\0\x2e\x72\x65\x6c\x2e\x42\x54\x46\0\x4c\x49\x43\x45\x4e\x53\x45\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x09\x01\0\0\x03\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x83\x0c\0\0\0\0\0\0\x32\x01\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x0f\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\x83\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x40\0\0\0\0\0\0\0\x50\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\x7f\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x90\x09\0\0\0\0\
\0\0\x10\0\0\0\0\0\0\0\x1a\0\0\0\x03\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\
\x19\x01\0\0\x01\0\0\0\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x90\0\0\0\0\0\0\0\x23\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xd5\0\0\0\x01\
\0\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xb3\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x3d\0\0\0\x01\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\xb7\0\0\0\0\0\0\0\x20\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\xd7\0\0\0\0\0\0\0\xfb\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\xbb\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xd2\x01\0\0\0\
\0\0\0\x0a\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\xb7\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xa0\x09\0\0\0\0\0\0\x50\
\0\0\0\0\0\0\0\x1a\0\0\0\x09\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x51\0\0\
\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xdc\x02\0\0\0\0\0\0\x60\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x4d\0\0\0\x09\0\0\0\x40\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xf0\x09\0\0\0\0\0\0\x60\x01\0\0\0\0\0\0\x1a\0\0\
\0\x0b\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x64\0\0\0\x01\0\0\0\x30\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\x3c\x03\0\0\0\0\0\0\xfe\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x01\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\xab\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\x3a\x04\0\0\0\0\0\0\x20\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\xa7\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x50\
\x0b\0\0\0\0\0\0\x30\0\0\0\0\0\0\0\x1a\0\0\0\x0e\0\0\0\x08\0\0\0\0\0\0\0\x10\0\
\0\0\0\0\0\0\x25\x01\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x5c\x04\0\0\
\0\0\0\0\x3a\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x21\x01\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x80\x0b\0\0\0\0\0\0\
\x20\0\0\0\0\0\0\0\x1a\0\0\0\x10\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x19\
\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x98\x06\0\0\0\0\0\0\x80\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x15\0\0\0\x09\0\0\0\
\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xa0\x0b\0\0\0\0\0\0\x50\0\0\0\0\0\0\0\x1a\0\
\0\0\x12\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\xf1\0\0\0\x01\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\x18\x07\0\0\0\0\0\0\x28\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xed\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\xf0\x0b\0\0\0\0\0\0\x20\0\0\0\0\0\0\0\x1a\0\0\0\x14\0\0\0\x08\0\0\0\
\0\0\0\0\x10\0\0\0\0\0\0\0\xe1\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x40\x07\0\0\0\0\0\0\x92\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\xdd\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x10\x0c\0\0\0\
\0\0\0\x70\0\0\0\0\0\0\0\x1a\0\0\0\x16\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\
\0\x6f\0\0\0\x01\0\0\0\x30\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xd2\x07\0\0\0\0\0\0\
\x52\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\xc7\0\0\
\0\x03\x4c\xff\x6f\0\0\0\x80\0\0\0\0\0\0\0\0\0\0\0\0\x80\x0c\0\0\0\0\0\0\x03\0\
\0\0\0\0\0\0\x1a\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x11\x01\0\0\
\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x28\x08\0\0\0\0\0\0\x68\x01\0\0\0\0\
\0\0\x01\0\0\0\x0d\0\0\0\x08\0\0\0\0\0\0\0\x18\0\0\0\0\0\0\0";

	*sz = sizeof(data) - 1;
	return (const void *)data;
}

#ifdef __cplusplus
struct test_ebpf *test_ebpf::open(const struct bpf_object_open_opts *opts) { return test_ebpf__open_opts(opts); }
struct test_ebpf *test_ebpf::open_and_load() { return test_ebpf__open_and_load(); }
int test_ebpf::load(struct test_ebpf *skel) { return test_ebpf__load(skel); }
int test_ebpf::attach(struct test_ebpf *skel) { return test_ebpf__attach(skel); }
void test_ebpf::detach(struct test_ebpf *skel) { test_ebpf__detach(skel); }
void test_ebpf::destroy(struct test_ebpf *skel) { test_ebpf__destroy(skel); }
const void *test_ebpf::elf_bytes(size_t *sz) { return test_ebpf__elf_bytes(sz); }
#endif /* __cplusplus */

__attribute__((unused)) static void
test_ebpf__assert(struct test_ebpf *s __attribute__((unused)))
{
#ifdef __cplusplus
#define _Static_assert static_assert
#endif
#ifdef __cplusplus
#undef _Static_assert
#endif
}

#endif /* __TEST_EBPF_SKEL_H__ */
